name: Jobs
on:
  workflow_call:
    inputs:
      payload:
        required: true
        type: string

jobs:
  morpheus-job:
    strategy:
      matrix:
        jobs: ${{ fromJSON(inputs.payload) }}
    uses: ./.github/workflows/sample.yaml
    with:
      key: ${{ matrix.jobs.value.key }}
      fruit: ${{ matrix.jobs.value.fruit }}
