name: Main
on:
  push:
  workflow_call:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      debug-enabled: ${{ steps.debug-check.outputs.enabled }}
      json: ${{ steps.generate.outputs.json }}
    steps:
      - id: generate
        shell: bash
        run: |
          printf '%s=%s\n' "json" '[[{"key":"foo","value":{"fruit":"orange"}}],[{"key":"bar","value":{"fruit":"apple"}}]]'  >> $GITHUB_OUTPUT

  example:
    needs:
      - bootstrap
    strategy:
      max-parallel: 1
      matrix:
        jobs: '${{ fromJSON(needs.bootstrap.outputs.json) }}'
    uses: ./.github/workflows/jobs.yaml
    with:
      payload: ${{ toJSON(matrix.jobs) }}
