name: Main
on:
  push:
  workflow_call:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      debug-enabled: ${{ steps.debug-check.outputs.enabled }}
      json: ${{ steps.generate.outputs.json }}
    steps:
      - id: generate
        shell: bash
        run: |
          printf '%s=%s\n' "json" '[[{"key":"a","value":{"fruit":"pineapple"}},{"key":"b","value":{"fruit":"orange"}},{"key":"c","value":{"fruit":"grapefruit"}},{"key":"d","value":{"fruit":"banana"}},{"key":"e","value":{"fruit":"kiwi"}},{"key":"f","value":{"fruit":"apple"}}],[{"key":"g","value":{"fruit":"dragonfruit"}},{"key":"h","value":{"fruit":"coconut"}},{"key":"i","value":{"fruit":"clementine"}},{"key":"j","value":{"fruit":"mango"}},{"key":"k","value":{"fruit":"strawberry"}},{"key":"l","value":{"fruit":"watermelon"}}]]'  >> $GITHUB_OUTPUT

  example:
    needs:
      - bootstrap
    strategy:
      max-parallel: 1
      matrix:
        jobs: '${{ fromJSON(needs.bootstrap.outputs.json) }}'
    uses: ./.github/workflows/jobs.yaml
    with:
      payload: ${{ toJSON(matrix.jobs) }}
